# Generated by Django 4.1.5 on 2023-01-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0001_initial_chargepoint_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargepoint',
            old_name='deleted',
            new_name='deleted_at',
        ),
    ]
